networks:
  roboshop:
    driver: bridge
services:
  mongodb:
    image: joindevops1/mongodb:v1
    container_name: mongodb
    networks:
    - roboshop
  catalogue:
    image: joindevops1/catalogue:v1
    container_name: catalogue
    networks:
    - roboshop
    depends_on:
    - mongodb
  redis:
     image: joindevops1/redis:v1
     container_name: redis
     networks:
     - roboshop
  user:
    image: joindevops1/user:v1
    container_name: user
    networks:
    - roboshop
    depends_on:
    - mongodb
    - redis
  cart:
    image: joindevops1/cart:v1
    container_name: cart
    networks:
    - roboshop
    depends_on:
    - redis
    - catalogue
  mysql:
    image: joindevops1/mysql:v1
    container_name: mysql
    networks:
    - roboshop
  shipping:
    image: joindevops1/shipping:v1
    container_name: shipping
    networks:
    - roboshop
    depends_on:
    - cart
    - mysql
  rabbitmq:
    image: joindevops1/rabbitmq
    container_name: rabbitmq
    networks:
    - roboshop
    environment:
    - RABBITMQ_DEFAULT_USER=roboshop 
    - RABBITMQ_DEFAULT_PASS=roboshop123

  payment:
    image: joindevops1/payment:v1
    container_name: payment
    networks:
    - roboshop
    depends_on:
    - cart
    - user
    - rabbitmq
  web:
     image: joindevops1/web:v1
     container_name: web
     networks:
     - roboshop
     ports:
     - "80:80"
     depends_on:
     - catalogue
     - user
     - cart
     - shipping
     - payment
